---
name: Test docker image

on:
  workflow_call:
    inputs:
      full-image-name:
        required: true
        type: string
      config-name:
        required: true
        type: string
      results-url:
        description: azure blob store path for results
        required: false
        default: "https://pactadatadev.blob.core.windows.net/ghactions-workflow-pacta-report-results"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout workflow
        uses: actions/checkout@v4

      - name: Prepare environment
        id: prepare
        env:
          CONFIG_NAME: ${{ inputs.config-name }}
        run: |
          config_file="tests/config/$CONFIG_NAME.json"
          echo "config_file: $config_file"

          HOLDINGS_DATE="$(jq -rc '.holdingsDate' $config_file)"
          echo "holdings-date=$HOLDINGS_DATE"
          echo "holdings-date=$HOLDINGS_DATE" >> "$GITHUB_OUTPUT"

          PACTA_DATA_URL="$(jq -rc '.pactaDataURL' $config_file)"
          echo "pacta-data-url=$PACTA_DATA_URL"
          echo "pacta-data-url=$PACTA_DATA_URL" >> "$GITHUB_OUTPUT"

          BENCHMARKS_URL="$(jq -rc '.benchmarksURL' $config_file)"
          echo "benchmarks-url=$BENCHMARKS_URL"
          echo "benchmarks-url=$BENCHMARKS_URL" >> "$GITHUB_OUTPUT"

          RESULTS_URL="$(jq -rc '.resultsURL' $config_file)"
          echo "results-url=$RESULTS_URL"
          echo "results-url=$RESULTS_URL" >> "$GITHUB_OUTPUT"

          # includes handling for null/missing keys
          PARAMETERS="$(jq -rc '.parameters | select( . != null )' $config_file)"
          echo "parameters=$PARAMETERS"
          echo "parameters=$PARAMETERS" >> "$GITHUB_OUTPUT"

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Download pacta-data
        uses: azure/CLI@v2
        env:
          PACTA_DATA_URL: ${{ steps.prepare.outputs.pacta-data-url }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            echo "pacta_data_dir: $PACTA_DATA_DATE_DIR"
            az storage copy \
              --source "$PACTA_DATA_URL/*" \
              --destination "pacta-data" \
              --recursive \
              --exclude-pattern "*.sqlite"

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Download Benchmark Results
        uses: azure/CLI@v2
        env:
          BENCHMARKS_URL: ${{ steps.prepare.outputs.benchmarks-url }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            az storage copy \
              --source "$BENCHMARKS_URL/*" \
              --destination "benchmarks_dir/" \
              --recursive \
              --exclude-pattern "*.sqlite"

      - name: Run Docker Image
        env:
          FULL_IMAGE_NAME: ${{ inputs.full-image-name }}
          WORKSPACE: ${{ github.workspace }}
          PARAMETERS: ${{ steps.prepare.outputs.parameters }}
          ANALYSIS_OUTPUT_DIR: analysis_output_dir
          BENCHMARKS_DIR: benchmarks_dir
          PACTA_DATA_DIR: pacta-data
          PORTFOLIO_DIR: tests/portfolios
          REAL_ESTATE_DIR: real_estate_dir
          REPORT_OUTPUT_DIR: report_output_dir
          SUMMARY_OUTPUT_DIR: summary_output_dir
          SURVEY_DIR: survey_dir
        run: |
          mkdir -p "$REPORT_OUTPUT_DIR"
          chmod -R 777 "$REPORT_OUTPUT_DIR"
          mkdir -p "$SUMMARY_OUTPUT_DIR"
          chmod -R 777 "$SUMMARY_OUTPUT_DIR"
          mkdir -p "$REAL_ESTATE_DIR"
          chmod -R 777 "$REAL_ESTATE_DIR"
          mkdir -p "$SURVEY_DIR"
          chmod -R 777 "$SURVEY_DIR"
          mkdir -p "$ANALYSIS_OUTPUT_DIR"
          chmod -R 777 "$ANALYSIS_OUTPUT_DIR"

          docker run \
          --network none \
          --env LOG_LEVEL=TRACE \
          --env ANALYSIS_OUTPUT_DIR="/mnt/analysis_output_dir" \
          --env OUTPUT_DIR="/mnt/analysis_output_dir" \
          --env BENCHMARKS_DIR="/mnt/benchmarks_dir" \
          --env PACTA_DATA_DIR="/mnt/pacta-data" \
          --env PORTFOLIO_DIR="/mnt/portfolios" \
          --env REPORT_OUTPUT_DIR="/mnt/report_output_dir" \
          --env SUMMARY_OUTPUT_DIR="/mnt/summary_output_dir" \
          --mount type=bind,readonly,source=${WORKSPACE}/${BENCHMARKS_DIR},target=/mnt/benchmarks_dir \
          --mount type=bind,readonly,source=${WORKSPACE}/${PACTA_DATA_DIR},target=/mnt/pacta-data \
          --mount type=bind,readonly,source=${WORKSPACE}/${PORTFOLIO_DIR},target=/mnt/portfolios \
          --mount type=bind,source=${WORKSPACE}/${ANALYSIS_OUTPUT_DIR},target=/mnt/analysis_output_dir \
          --mount type=bind,source=${WORKSPACE}/${REPORT_OUTPUT_DIR},target=/mnt/report_output_dir \
          --mount type=bind,source=${WORKSPACE}/${SUMMARY_OUTPUT_DIR},target=/mnt/summary_output_dir \
          $FULL_IMAGE_NAME \
          "$PARAMETERS"

      - name: List outputs
        run: |
          ls -lR report_output_dir
          ls -lR summary_output_dir

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Upload results to blob store
        id: upload
        uses: azure/CLI@v2
        env:
          CONFIG_NAME: ${{ inputs.config-name }}
          GITHUB_REF_NAME: ${{ github.ref_name}}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          REPORT_OUTPUT_DIR: report_output_dir
          SUMMARY_OUTPUT_DIR: summary_output_dir
          RESULTS_URL: ${{ inputs.results-url }}
        with:
          inlineScript: |
            unique_directory="$RESULTS_URL/$GITHUB_REF_NAME/$GITHUB_RUN_NUMBER/$GITHUB_RUN_ATTEMPT/$CONFIG_NAME"
            az storage copy \
              --source "$REPORT_OUTPUT_DIR"/* \
              --destination "$unique_directory" \
              --recursive
            echo "report-url=${unique_directory}/report/index.html" >> "$GITHUB_OUTPUT"

            az storage copy \
              --source "$SUMMARY_OUTPUT_DIR"/* \
              --destination "$unique_directory" \
              --recursive
            summary_files="$(ls $SUMMARY_OUTPUT_DIR/executive_summary/*.pdf)"
            echo "summary-url=${unique_directory}/executive_summary/$summary_files" >> "$GITHUB_OUTPUT"

      - name: Prepare comment artifact
        id: prepare-artifact
        env:
          commit_time: ${{ github.event.pull_request.updated_at }}
          config_name: ${{ inputs.config-name }}
          full_image_name: ${{ inputs.full-image-name }}
          git_sha: ${{ github.event.pull_request.head.sha }}
          report_url: ${{ steps.upload.outputs.report-url }}
          summary_url: ${{ steps.upload.outputs.summary-url }}
        run: |
          mkdir -p /tmp/comment-json
          json_filename="$( \
            echo "report-comment-json-merge-$full_image_name-$config_name" | \
            tr '/:._' '-' \
            ).json"
          echo "json-filename=$json_filename" >> "$GITHUB_OUTPUT"
          json_file="/tmp/comment-json/$json_filename"
          jq \
            -n \
            --arg commit_time "$commit_time" \
            --arg config_name "$config_name" \
            --arg git_sha "$git_sha" \
            --arg report_url "$report_url" \
            --arg summary_url "$summary_url" \
            --arg full_image_name "$full_image_name" \
            '{
              "commit_time": $commit_time,
              "git_sha": $git_sha,
              "config": $config_name,
              "report": ("[Report](" + $report_url + ")"),
              "summary": (if (("" + $summary_url) == "") then null else "[Summary](" + $summary_url + ")" end),
              "image": ("`" + $full_image_name + "`")
            }' \
          >> $json_file
          cat "$json_file"

      - name: Upload comment JSON
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare-artifact.outputs.json-filename }}
          path: /tmp/comment-json/*
          if-no-files-found: error
          retention-days: 1
